- name: Install pip and Python venv
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
        state: present
        update_cache: yes

    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Install pip for Python 3
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Verify pip installation
      ansible.builtin.command: pip3 --version
      register: pip_version

    - name: Display pip version
      ansible.builtin.debug:
        msg: "pip version: {{ pip_version.stdout }}"