
- name: Install basics
  hosts: all
  become: yes
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes
    - name: Ensure wget is installed
      ansible.builtin.apt:
        name: wget
        state: present
    - name: Ensure ansible-lint is installed
      ansible.builtin.apt:
        name: ansible-lint
        state: present
